export enum NotificationType {
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  RETURN_UPDATE = 'RETURN_UPDATE',
  TICKET_REPLY = 'TICKET_REPLY',
  LOYALTY_EARNED = 'LOYALTY_EARNED',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  LOW_STOCK = 'LOW_STOCK',
  PROMOTION = 'PROMOTION',
}
